import 'dart:async';
import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

import 'dao/task_dao.dart';
import 'dao/room_dao.dart';
import 'entities/task_entity.dart';
import 'entities/room_entity.dart';

part 'app_database.g.dart'; // generated by build_runner

@Database(
        version: 1,
entities: [TaskEntity, RoomEntity],
        )
abstract class AppDatabase extends FloorDatabase {
    TaskDao get taskDao;
    RoomDao get roomDao;

    /// Singleton instance
    static AppDatabase? _instance;

    static Future<AppDatabase> getInstance() async {
        _instance ??= await $FloorAppDatabase
                .databaseBuilder('don_nha_don_tet.db')
                .addMigrations([]) // thêm migration khi nâng version
        .build();
        return _instance!;
    }
}